name: Restore Jest cache
description: Restore the Jest transform cache.

runs:
  using: composite
  steps:
    - name: Restore Jest cache
      uses: actions/cache@v4
      with:
        path: node_modules/.cache/jest
        key: jest-${{ runner.os }}-${{ hashFiles('package-lock.json', 'jest.config.js') }}
        restore-keys: |
          jest-${{ runner.os }}-
